# Generated by Django 4.2.2 on 2023-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='submissions',
            new_name='submission',
        ),
    ]
